version: "3.3"
services:
  api:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./api/:/var/www/html/"
    ports:
      - "3000:80"
  new_api:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./new_api/:/var/www/html/"
    ports:
      - "7000:80"
  frontend:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./frontend/:/var/www/html/"
    ports:
      - "4001:80"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "30002:80"
volumes:
  mysql-data:
