<h1 class="text-center">WEBHOOK Details</h1>

<form action ="/webhook/webhook" action ="post">
  <div class="form-group">
    <label for="exampleInputEmail1">Enter name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
    name="url" placeholder="Enter url">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Enter event</label>
    <input type="event" class="form-control" id="exampleInputPassword1" name="event" placeholder="Event">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Enter key</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="key" placeholder="key">
  </div>
 
  <button type="submit" class="btn btn-primary">Submit</button>
</form>