<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
                        <form action="/signup/register" method="POST">

                            <div class="row">
                                <div class="col-md-12 mb-4">

                                    <div class="form-outline">
                                        <input type="text" id="name" name="name" class="form-control form-control-lg" />
                                        <label class="form-label">Name</label>
                                    </div>

                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-12 mb-4 ">

                                    <div class="form-outline">
                                        <input type="email" id="email" name="email"
                                        class="form-control form-control-lg" />
                                        <label class="form-label" for="emailAddress">Email</label>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 mb-4">

                                    <div class="form-outline">
                                        <input type="text" id="password" name="password"
                                         class="form-control form-control-lg" />
                                        <label class="form-label" for="phoneNumber">Password</label>
                                    </div>

                                </div>
                            </div>

                            <div class="form-check d-flex  mb-5">
                                <P>REMEMBER ME</P>
                                <input class="form-check-input me-2" type="checkbox"
                                 name="remember" value="1" id="form2Example3c">
                                <div class="mt-4 pt-2">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                                    <button type="button" class="btn btn-outline-dark">
                                        <?php
                                        
                                        echo $this->tag->linkTO(["login/index","Login","class"=>"btn btn-info "]);
                                        ?>
                                       
                                    </button>
                                </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>